package com.peny.po;

import java.io.Serializable;

public class Activity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityId
     *
     * @mbggenerated
     */
    private Integer activityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityName
     *
     * @mbggenerated
     */
    private String activityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityDes
     *
     * @mbggenerated
     */
    private String activitydes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.discount
     *
     * @mbggenerated
     */
    private Float discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.fullPrice
     *
     * @mbggenerated
     */
    private Integer fullprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.reducePrice
     *
     * @mbggenerated
     */
    private Integer reduceprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.fullNum
     *
     * @mbggenerated
     */
    private Integer fullnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.reduceNum
     *
     * @mbggenerated
     */
    private Integer reducenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityId
     *
     * @return the value of activity.activityId
     *
     * @mbggenerated
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityId
     *
     * @param activityid the value for activity.activityId
     *
     * @mbggenerated
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityName
     *
     * @return the value of activity.activityName
     *
     * @mbggenerated
     */
    public String getActivityname() {
        return activityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityName
     *
     * @param activityname the value for activity.activityName
     *
     * @mbggenerated
     */
    public void setActivityname(String activityname) {
        this.activityname = activityname == null ? null : activityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityDes
     *
     * @return the value of activity.activityDes
     *
     * @mbggenerated
     */
    public String getActivitydes() {
        return activitydes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityDes
     *
     * @param activitydes the value for activity.activityDes
     *
     * @mbggenerated
     */
    public void setActivitydes(String activitydes) {
        this.activitydes = activitydes == null ? null : activitydes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.discount
     *
     * @return the value of activity.discount
     *
     * @mbggenerated
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.discount
     *
     * @param discount the value for activity.discount
     *
     * @mbggenerated
     */
    public void setDiscount(Float discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.fullPrice
     *
     * @return the value of activity.fullPrice
     *
     * @mbggenerated
     */
    public Integer getFullprice() {
        return fullprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.fullPrice
     *
     * @param fullprice the value for activity.fullPrice
     *
     * @mbggenerated
     */
    public void setFullprice(Integer fullprice) {
        this.fullprice = fullprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.reducePrice
     *
     * @return the value of activity.reducePrice
     *
     * @mbggenerated
     */
    public Integer getReduceprice() {
        return reduceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.reducePrice
     *
     * @param reduceprice the value for activity.reducePrice
     *
     * @mbggenerated
     */
    public void setReduceprice(Integer reduceprice) {
        this.reduceprice = reduceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.fullNum
     *
     * @return the value of activity.fullNum
     *
     * @mbggenerated
     */
    public Integer getFullnum() {
        return fullnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.fullNum
     *
     * @param fullnum the value for activity.fullNum
     *
     * @mbggenerated
     */
    public void setFullnum(Integer fullnum) {
        this.fullnum = fullnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.reduceNum
     *
     * @return the value of activity.reduceNum
     *
     * @mbggenerated
     */
    public Integer getReducenum() {
        return reducenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.reduceNum
     *
     * @param reducenum the value for activity.reduceNum
     *
     * @mbggenerated
     */
    public void setReducenum(Integer reducenum) {
        this.reducenum = reducenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Activity other = (Activity) that;
        return (this.getActivityid() == null ? other.getActivityid() == null : this.getActivityid().equals(other.getActivityid()))
            && (this.getActivityname() == null ? other.getActivityname() == null : this.getActivityname().equals(other.getActivityname()))
            && (this.getActivitydes() == null ? other.getActivitydes() == null : this.getActivitydes().equals(other.getActivitydes()))
            && (this.getDiscount() == null ? other.getDiscount() == null : this.getDiscount().equals(other.getDiscount()))
            && (this.getFullprice() == null ? other.getFullprice() == null : this.getFullprice().equals(other.getFullprice()))
            && (this.getReduceprice() == null ? other.getReduceprice() == null : this.getReduceprice().equals(other.getReduceprice()))
            && (this.getFullnum() == null ? other.getFullnum() == null : this.getFullnum().equals(other.getFullnum()))
            && (this.getReducenum() == null ? other.getReducenum() == null : this.getReducenum().equals(other.getReducenum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getActivityid() == null) ? 0 : getActivityid().hashCode());
        result = prime * result + ((getActivityname() == null) ? 0 : getActivityname().hashCode());
        result = prime * result + ((getActivitydes() == null) ? 0 : getActivitydes().hashCode());
        result = prime * result + ((getDiscount() == null) ? 0 : getDiscount().hashCode());
        result = prime * result + ((getFullprice() == null) ? 0 : getFullprice().hashCode());
        result = prime * result + ((getReduceprice() == null) ? 0 : getReduceprice().hashCode());
        result = prime * result + ((getFullnum() == null) ? 0 : getFullnum().hashCode());
        result = prime * result + ((getReducenum() == null) ? 0 : getReducenum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", activityid=").append(activityid);
        sb.append(", activityname=").append(activityname);
        sb.append(", activitydes=").append(activitydes);
        sb.append(", discount=").append(discount);
        sb.append(", fullprice=").append(fullprice);
        sb.append(", reduceprice=").append(reduceprice);
        sb.append(", fullnum=").append(fullnum);
        sb.append(", reducenum=").append(reducenum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}