package com.peny.po;

import java.io.Serializable;
import java.util.Date;

public class Chat implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.chatId
     *
     * @mbggenerated
     */
    private Integer chatid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.sendUser
     *
     * @mbggenerated
     */
    private Integer senduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.receiveUser
     *
     * @mbggenerated
     */
    private Integer receiveuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.MsgContent
     *
     * @mbggenerated
     */
    private String msgcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.MsgTime
     *
     * @mbggenerated
     */
    private Date msgtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chatId
     *
     * @return the value of chat.chatId
     *
     * @mbggenerated
     */
    public Integer getChatid() {
        return chatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chatId
     *
     * @param chatid the value for chat.chatId
     *
     * @mbggenerated
     */
    public void setChatid(Integer chatid) {
        this.chatid = chatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.sendUser
     *
     * @return the value of chat.sendUser
     *
     * @mbggenerated
     */
    public Integer getSenduser() {
        return senduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.sendUser
     *
     * @param senduser the value for chat.sendUser
     *
     * @mbggenerated
     */
    public void setSenduser(Integer senduser) {
        this.senduser = senduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.receiveUser
     *
     * @return the value of chat.receiveUser
     *
     * @mbggenerated
     */
    public Integer getReceiveuser() {
        return receiveuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.receiveUser
     *
     * @param receiveuser the value for chat.receiveUser
     *
     * @mbggenerated
     */
    public void setReceiveuser(Integer receiveuser) {
        this.receiveuser = receiveuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.MsgContent
     *
     * @return the value of chat.MsgContent
     *
     * @mbggenerated
     */
    public String getMsgcontent() {
        return msgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.MsgContent
     *
     * @param msgcontent the value for chat.MsgContent
     *
     * @mbggenerated
     */
    public void setMsgcontent(String msgcontent) {
        this.msgcontent = msgcontent == null ? null : msgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.MsgTime
     *
     * @return the value of chat.MsgTime
     *
     * @mbggenerated
     */
    public Date getMsgtime() {
        return msgtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.MsgTime
     *
     * @param msgtime the value for chat.MsgTime
     *
     * @mbggenerated
     */
    public void setMsgtime(Date msgtime) {
        this.msgtime = msgtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Chat other = (Chat) that;
        return (this.getChatid() == null ? other.getChatid() == null : this.getChatid().equals(other.getChatid()))
            && (this.getSenduser() == null ? other.getSenduser() == null : this.getSenduser().equals(other.getSenduser()))
            && (this.getReceiveuser() == null ? other.getReceiveuser() == null : this.getReceiveuser().equals(other.getReceiveuser()))
            && (this.getMsgcontent() == null ? other.getMsgcontent() == null : this.getMsgcontent().equals(other.getMsgcontent()))
            && (this.getMsgtime() == null ? other.getMsgtime() == null : this.getMsgtime().equals(other.getMsgtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChatid() == null) ? 0 : getChatid().hashCode());
        result = prime * result + ((getSenduser() == null) ? 0 : getSenduser().hashCode());
        result = prime * result + ((getReceiveuser() == null) ? 0 : getReceiveuser().hashCode());
        result = prime * result + ((getMsgcontent() == null) ? 0 : getMsgcontent().hashCode());
        result = prime * result + ((getMsgtime() == null) ? 0 : getMsgtime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chatid=").append(chatid);
        sb.append(", senduser=").append(senduser);
        sb.append(", receiveuser=").append(receiveuser);
        sb.append(", msgcontent=").append(msgcontent);
        sb.append(", msgtime=").append(msgtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}