package com.peny.po;

import java.io.Serializable;

public class Deliver implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliver.deliverId
     *
     * @mbggenerated
     */
    private Integer deliverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliver.orderId
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliver.sendId
     *
     * @mbggenerated
     */
    private Integer sendid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliver
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliver.deliverId
     *
     * @return the value of deliver.deliverId
     *
     * @mbggenerated
     */
    public Integer getDeliverid() {
        return deliverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliver.deliverId
     *
     * @param deliverid the value for deliver.deliverId
     *
     * @mbggenerated
     */
    public void setDeliverid(Integer deliverid) {
        this.deliverid = deliverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliver.orderId
     *
     * @return the value of deliver.orderId
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliver.orderId
     *
     * @param orderid the value for deliver.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliver.sendId
     *
     * @return the value of deliver.sendId
     *
     * @mbggenerated
     */
    public Integer getSendid() {
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliver.sendId
     *
     * @param sendid the value for deliver.sendId
     *
     * @mbggenerated
     */
    public void setSendid(Integer sendid) {
        this.sendid = sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliver
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Deliver other = (Deliver) that;
        return (this.getDeliverid() == null ? other.getDeliverid() == null : this.getDeliverid().equals(other.getDeliverid()))
            && (this.getOrderid() == null ? other.getOrderid() == null : this.getOrderid().equals(other.getOrderid()))
            && (this.getSendid() == null ? other.getSendid() == null : this.getSendid().equals(other.getSendid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliver
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDeliverid() == null) ? 0 : getDeliverid().hashCode());
        result = prime * result + ((getOrderid() == null) ? 0 : getOrderid().hashCode());
        result = prime * result + ((getSendid() == null) ? 0 : getSendid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliver
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deliverid=").append(deliverid);
        sb.append(", orderid=").append(orderid);
        sb.append(", sendid=").append(sendid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}