package com.peny.po;

import java.io.Serializable;
import java.util.Date;

public class Indent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.orderId
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.orderTime
     *
     * @mbggenerated
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.oldPrice
     *
     * @mbggenerated
     */
    private Float oldprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.newPrice
     *
     * @mbggenerated
     */
    private Float newprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.isPay
     *
     * @mbggenerated
     */
    private Boolean ispay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.isSend
     *
     * @mbggenerated
     */
    private Boolean issend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.isReceive
     *
     * @mbggenerated
     */
    private Boolean isreceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.isComplete
     *
     * @mbggenerated
     */
    private Boolean iscomplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.addressId
     *
     * @mbggenerated
     */
    private Integer addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indent
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.orderId
     *
     * @return the value of indent.orderId
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.orderId
     *
     * @param orderid the value for indent.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.userId
     *
     * @return the value of indent.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.userId
     *
     * @param userid the value for indent.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.orderTime
     *
     * @return the value of indent.orderTime
     *
     * @mbggenerated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.orderTime
     *
     * @param ordertime the value for indent.orderTime
     *
     * @mbggenerated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.oldPrice
     *
     * @return the value of indent.oldPrice
     *
     * @mbggenerated
     */
    public Float getOldprice() {
        return oldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.oldPrice
     *
     * @param oldprice the value for indent.oldPrice
     *
     * @mbggenerated
     */
    public void setOldprice(Float oldprice) {
        this.oldprice = oldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.newPrice
     *
     * @return the value of indent.newPrice
     *
     * @mbggenerated
     */
    public Float getNewprice() {
        return newprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.newPrice
     *
     * @param newprice the value for indent.newPrice
     *
     * @mbggenerated
     */
    public void setNewprice(Float newprice) {
        this.newprice = newprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.isPay
     *
     * @return the value of indent.isPay
     *
     * @mbggenerated
     */
    public Boolean getIspay() {
        return ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.isPay
     *
     * @param ispay the value for indent.isPay
     *
     * @mbggenerated
     */
    public void setIspay(Boolean ispay) {
        this.ispay = ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.isSend
     *
     * @return the value of indent.isSend
     *
     * @mbggenerated
     */
    public Boolean getIssend() {
        return issend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.isSend
     *
     * @param issend the value for indent.isSend
     *
     * @mbggenerated
     */
    public void setIssend(Boolean issend) {
        this.issend = issend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.isReceive
     *
     * @return the value of indent.isReceive
     *
     * @mbggenerated
     */
    public Boolean getIsreceive() {
        return isreceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.isReceive
     *
     * @param isreceive the value for indent.isReceive
     *
     * @mbggenerated
     */
    public void setIsreceive(Boolean isreceive) {
        this.isreceive = isreceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.isComplete
     *
     * @return the value of indent.isComplete
     *
     * @mbggenerated
     */
    public Boolean getIscomplete() {
        return iscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.isComplete
     *
     * @param iscomplete the value for indent.isComplete
     *
     * @mbggenerated
     */
    public void setIscomplete(Boolean iscomplete) {
        this.iscomplete = iscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.addressId
     *
     * @return the value of indent.addressId
     *
     * @mbggenerated
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.addressId
     *
     * @param addressid the value for indent.addressId
     *
     * @mbggenerated
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Indent other = (Indent) that;
        return (this.getOrderid() == null ? other.getOrderid() == null : this.getOrderid().equals(other.getOrderid()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getOrdertime() == null ? other.getOrdertime() == null : this.getOrdertime().equals(other.getOrdertime()))
            && (this.getOldprice() == null ? other.getOldprice() == null : this.getOldprice().equals(other.getOldprice()))
            && (this.getNewprice() == null ? other.getNewprice() == null : this.getNewprice().equals(other.getNewprice()))
            && (this.getIspay() == null ? other.getIspay() == null : this.getIspay().equals(other.getIspay()))
            && (this.getIssend() == null ? other.getIssend() == null : this.getIssend().equals(other.getIssend()))
            && (this.getIsreceive() == null ? other.getIsreceive() == null : this.getIsreceive().equals(other.getIsreceive()))
            && (this.getIscomplete() == null ? other.getIscomplete() == null : this.getIscomplete().equals(other.getIscomplete()))
            && (this.getAddressid() == null ? other.getAddressid() == null : this.getAddressid().equals(other.getAddressid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderid() == null) ? 0 : getOrderid().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getOrdertime() == null) ? 0 : getOrdertime().hashCode());
        result = prime * result + ((getOldprice() == null) ? 0 : getOldprice().hashCode());
        result = prime * result + ((getNewprice() == null) ? 0 : getNewprice().hashCode());
        result = prime * result + ((getIspay() == null) ? 0 : getIspay().hashCode());
        result = prime * result + ((getIssend() == null) ? 0 : getIssend().hashCode());
        result = prime * result + ((getIsreceive() == null) ? 0 : getIsreceive().hashCode());
        result = prime * result + ((getIscomplete() == null) ? 0 : getIscomplete().hashCode());
        result = prime * result + ((getAddressid() == null) ? 0 : getAddressid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderid=").append(orderid);
        sb.append(", userid=").append(userid);
        sb.append(", ordertime=").append(ordertime);
        sb.append(", oldprice=").append(oldprice);
        sb.append(", newprice=").append(newprice);
        sb.append(", ispay=").append(ispay);
        sb.append(", issend=").append(issend);
        sb.append(", isreceive=").append(isreceive);
        sb.append(", iscomplete=").append(iscomplete);
        sb.append(", addressid=").append(addressid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}