package com.peny.po;

import java.io.Serializable;
import java.util.Date;

public class Shopcart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcart.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcart.goodsid
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcart.cateDate
     *
     * @mbggenerated
     */
    private Date catedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcart.goodsNum
     *
     * @mbggenerated
     */
    private Integer goodsnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcart.userId
     *
     * @return the value of shopcart.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcart.userId
     *
     * @param userid the value for shopcart.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcart.goodsid
     *
     * @return the value of shopcart.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcart.goodsid
     *
     * @param goodsid the value for shopcart.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcart.cateDate
     *
     * @return the value of shopcart.cateDate
     *
     * @mbggenerated
     */
    public Date getCatedate() {
        return catedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcart.cateDate
     *
     * @param catedate the value for shopcart.cateDate
     *
     * @mbggenerated
     */
    public void setCatedate(Date catedate) {
        this.catedate = catedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcart.goodsNum
     *
     * @return the value of shopcart.goodsNum
     *
     * @mbggenerated
     */
    public Integer getGoodsnum() {
        return goodsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcart.goodsNum
     *
     * @param goodsnum the value for shopcart.goodsNum
     *
     * @mbggenerated
     */
    public void setGoodsnum(Integer goodsnum) {
        this.goodsnum = goodsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Shopcart other = (Shopcart) that;
        return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getGoodsid() == null ? other.getGoodsid() == null : this.getGoodsid().equals(other.getGoodsid()))
            && (this.getCatedate() == null ? other.getCatedate() == null : this.getCatedate().equals(other.getCatedate()))
            && (this.getGoodsnum() == null ? other.getGoodsnum() == null : this.getGoodsnum().equals(other.getGoodsnum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getGoodsid() == null) ? 0 : getGoodsid().hashCode());
        result = prime * result + ((getCatedate() == null) ? 0 : getCatedate().hashCode());
        result = prime * result + ((getGoodsnum() == null) ? 0 : getGoodsnum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", goodsid=").append(goodsid);
        sb.append(", catedate=").append(catedate);
        sb.append(", goodsnum=").append(goodsnum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}