package com.peny.mapper;



import com.peny.po.Deliver;
import com.peny.po.DeliverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeliverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliver
     *
     * @mbggenerated
     */
    int countByExample(DeliverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliver
     *
     * @mbggenerated
     */
    int deleteByExample(DeliverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliver
     *
     * @mbggenerated
     */
    int insert(Deliver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliver
     *
     * @mbggenerated
     */
    int insertSelective(Deliver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliver
     *
     * @mbggenerated
     */
    List<Deliver> selectByExample(DeliverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliver
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Deliver record, @Param("example") DeliverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliver
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Deliver record, @Param("example") DeliverExample example);
}