package com.peny.mapper;



import com.peny.po.Imagepath;
import com.peny.po.ImagepathExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImagepathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagepath
     *
     * @mbggenerated
     */
    int countByExample(ImagepathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagepath
     *
     * @mbggenerated
     */
    int deleteByExample(ImagepathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagepath
     *
     * @mbggenerated
     */
    int insert(Imagepath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagepath
     *
     * @mbggenerated
     */
    int insertSelective(Imagepath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagepath
     *
     * @mbggenerated
     */
    List<Imagepath> selectByExample(ImagepathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagepath
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Imagepath record, @Param("example") ImagepathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagepath
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Imagepath record, @Param("example") ImagepathExample example);
}