package com.peny.mapper;



import com.peny.po.Indent;
import com.peny.po.IndentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated
     */
    int countByExample(IndentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated
     */
    int deleteByExample(IndentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated
     */
    int insert(Indent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated
     */
    int insertSelective(Indent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated
     */
    List<Indent> selectByExample(IndentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Indent record, @Param("example") IndentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Indent record, @Param("example") IndentExample example);
}