package com.peny.mapper;

import com.peny.po.Shopcart;
import com.peny.po.ShopcartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopcartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int countByExample(ShopcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int deleteByExample(ShopcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int insert(Shopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int insertSelective(Shopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    List<Shopcart> selectByExample(ShopcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Shopcart record, @Param("example") ShopcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Shopcart record, @Param("example") ShopcartExample example);
}